-- 026_exam_set_foundation.sql
-- Document-based Exam Set foundation (SAFE milestone).
--
-- Scope (per spec, with user-approved adjustments):
--   1. questions.question_code  — unique, indexed, IMMUTABLE business identifier.
--      Format Q-000001 (zero-padded sequential). Generated by the IMPORTER only
--      (app/admin/import/actions.ts), via allocate_question_codes(n). The DB
--      does NOT default-fill the column, so no other insert path (manual SQL,
--      RPCs, future admin screens) can mint a code. A BEFORE UPDATE trigger
--      makes it immutable once written (NULL -> value is the only change).
--
--   2. exam_sets lifecycle columns — additive only. No destructive changes.
--        exam_type   'document' | 'simulation'  (default 'document'; simulation
--                    path is OUT OF SCOPE for this milestone)
--        status      'draft' | 'published' | 'archived'  (default 'draft')
--        subject     text   (value SELECTED from Question Bank metadata,
--        document    text    i.e. get_question_metadata() — never free-form)
--      slug and question_count are INTENTIONALLY OMITTED:
--        - slug            : public exam routing is by UUID examSetId
--                            (app/package/[slug]/exam/[examSetId]); no slug needed.
--        - question_count  : exam_set_questions is the source of truth; COUNT(*)
--                            is computed on demand. Caching deferred to a later
--                            milestone if perf ever requires it.
--
--   3. validate_exam_set_for_publish(uuid) — read-only SECURITY DEFINER RPC that
--      enforces the publish rules (>=1 question, no duplicate questions, unique
--      sort_order). Mirrors the read-only RPC style of migrations 016/021/022.
--      The write (UPDATE exam_sets.status) is performed by the server action
--      after this RPC returns valid=true, so RLS remains the write authority.
--
-- Reuse: exam_set_questions.sort_order (migration 001) is the spec's
--        "display_order". No new junction column. The composite PK
--        (exam_set_id, question_id) already guarantees question membership is
--        unique; sort_order uniqueness is checked at publish time.
--
-- No FK targets exist for subject/document (migration 019 explicitly defers a
-- documents table), so these are plain text columns — chosen from Question Bank
-- metadata, which makes a future migration to normalized lookup tables trivial.
--
-- Safe to re-run: every statement is IF NOT EXISTS / OR REPLACE.

-- ════════════════════════════════════════════════════════════════════════
-- 1. question_code
-- ════════════════════════════════════════════════════════════════════════

-- Dedicated SEQUENCE for stable, gap-tolerant sequential numbering.
-- Starts at 1 so the first code is Q-000001. Cached for insert throughput.
CREATE SEQUENCE IF NOT EXISTS public.question_code_seq
  AS bigint START 1 INCREMENT 1 MINVALUE 1 NO CYCLE CACHE 10;

ALTER TABLE public.questions
  ADD COLUMN IF NOT EXISTS question_code text;

-- Unique index (not a column constraint) so pre-existing rows with NULL codes
-- coexist. A plain UNIQUE column constraint would also allow multiple NULLs in
-- Postgres, but an explicit index matches how package_code-style lookups are
-- indexed elsewhere in the schema.
CREATE UNIQUE INDEX IF NOT EXISTS questions_question_code_key
  ON public.questions (question_code);

-- SINGLE SOURCE OF TRUTH for the code format. Everything that needs to render a
-- question code string calls this function — there is no second copy of the
-- format anywhere (SQL or TS). If the business identifier format ever changes
-- (prefix, padding, length), only this function is edited.
--
-- Pure / IMMUTABLE-equivalent: depends solely on its argument. Marked STABLE so
-- the planner may inline it in read queries.
CREATE OR REPLACE FUNCTION public.format_question_code(seq_value bigint)
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT 'Q-' || lpad(seq_value::text, 6, '0')
$$;

-- Immutability: once a code is set it can NEVER change. NULL -> <value> is the
-- only permitted transition (the importer writes it exactly once at insert).
-- Any attempt to overwrite a non-null value raises, protecting the business
-- identifier guarantee even from admins / future code paths.
CREATE OR REPLACE FUNCTION public.protect_question_code()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.question_code IS NOT NULL
     AND NEW.question_code IS DISTINCT FROM OLD.question_code THEN
    RAISE EXCEPTION 'question_code is immutable (current value: %)', OLD.question_code
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_question_code ON public.questions;
CREATE TRIGGER protect_question_code
  BEFORE UPDATE ON public.questions
  FOR EACH ROW EXECUTE FUNCTION public.protect_question_code();

-- allocate_question_codes(n)
-- ---------------------------------------------------------------------------
-- IDENTIFIER ALLOCATION FUNCTION ONLY.
--
-- Sole responsibility: advance question_code_seq n times and return n formatted,
-- immutable question codes (Q-000001, Q-000002, ...).
--
-- It deliberately performs NO other work:
--   - It does NOT insert Question rows.
--   - It does NOT read or write any Question business column
--     (content, choices, difficulty, subject, ...).
--   - It does NOT validate question content.
--   - It has NO knowledge of what the codes will be attached to.
--
-- Merging a returned code into a Question row is the CALLER's responsibility
-- (the importer, app/admin/import/actions.ts). This separation guarantees the
-- function's only DB side-effect is sequence advancement.
--
-- SECURITY DEFINER so the calling role needs only EXECUTE (not USAGE on the
-- sequence). Granted to authenticated (admin-only in practice — the importer is
-- gated by requirePermission('content.write')).
--
-- Side effect: nextval is not rollback-safe for gaps. If the caller's subsequent
-- batch insert fails after allocation, those sequence values are consumed and
-- the code series will have a gap. This is acceptable: the code remains stable,
-- sortable, and immutable. It is identical to the gap any failed insert leaves.
CREATE OR REPLACE FUNCTION public.allocate_question_codes(n integer)
RETURNS text[]
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  codes text[];
BEGIN
  IF n IS NULL OR n <= 0 THEN
    RETURN ARRAY[]::text[];
  END IF;

  SELECT array_agg(public.format_question_code(nextval('public.question_code_seq')))
  INTO codes
  FROM generate_series(1, n);

  RETURN codes;
END;
$$;

GRANT EXECUTE ON FUNCTION public.allocate_question_codes(integer) TO authenticated;

-- ════════════════════════════════════════════════════════════════════════
-- 2. exam_sets lifecycle columns (additive)
-- ════════════════════════════════════════════════════════════════════════

ALTER TABLE public.exam_sets
  ADD COLUMN IF NOT EXISTS exam_type text NOT NULL DEFAULT 'document'
    CHECK (exam_type IN ('document', 'simulation')),
  ADD COLUMN IF NOT EXISTS status    text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'published', 'archived')),
  ADD COLUMN IF NOT EXISTS subject   text,
  ADD COLUMN IF NOT EXISTS document  text;

CREATE INDEX IF NOT EXISTS exam_sets_status_idx ON public.exam_sets (status);

-- ════════════════════════════════════════════════════════════════════════
-- 3. validate_exam_set_for_publish(uuid)
-- ════════════════════════════════════════════════════════════════════════

-- Enforces the three publish rules atomically in Postgres:
--   (a) at least one question
--   (b) no duplicate questions  (already structurally guaranteed by the
--       composite PK on exam_set_questions; kept for an explicit error_code)
--   (c) unique sort_order within the set  (sort_order is the spec's
--       "display_order", reused from migration 001)
-- Returns one row: (valid, error_code, message). Read-only; the server action
-- performs the actual status UPDATE after valid=true.
--
-- Style mirrors get_package_public_counts (016) / get_question_usage_counts (021)
-- / get_question_metadata (022): SECURITY DEFINER, set search_path, granted to
-- authenticated.
CREATE OR REPLACE FUNCTION public.validate_exam_set_for_publish(p_exam_set_id uuid)
RETURNS TABLE(valid boolean, error_code text, message text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  WITH counts AS (
    SELECT
      count(*)                          AS total,
      count(DISTINCT question_id)       AS distinct_questions,
      count(DISTINCT sort_order)        AS distinct_orders
    FROM exam_set_questions
    WHERE exam_set_id = p_exam_set_id
  )
  SELECT
    CASE
      WHEN total = 0                       THEN false
      WHEN distinct_questions <> total     THEN false
      WHEN distinct_orders    <> total     THEN false
      ELSE true
    END AS valid,
    CASE
      WHEN total = 0                       THEN 'no_questions'::text
      WHEN distinct_questions <> total     THEN 'duplicate_questions'::text
      WHEN distinct_orders    <> total     THEN 'duplicate_order'::text
      ELSE NULL
    END AS error_code,
    CASE
      WHEN total = 0                       THEN 'Exam Set must contain at least one question.'::text
      WHEN distinct_questions <> total     THEN 'Exam Set contains duplicate questions.'::text
      WHEN distinct_orders    <> total     THEN 'Display order values must be unique.'::text
      ELSE NULL
    END AS message
  FROM counts;
$$;

GRANT EXECUTE ON FUNCTION public.validate_exam_set_for_publish(uuid) TO authenticated;
