import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const migration = readFileSync(
  join(dirname(fileURLToPath(import.meta.url)), '103_payment_verification_m1_3_expand.sql'),
  'utf8',
)

test('M1.3A migration is additive, shadow-defaulted, and keeps manual RPC signatures', () => {
  assert.match(migration, /add column auto_approval_enabled boolean not null default false/i)
  assert.match(migration, /migration runner supplies the transaction boundary/i)
  assert.match(migration, /set local search_path = public/i)
  assert.match(migration, /add column legacy_replay_backfill_complete boolean not null default false/i)
  assert.match(migration, /legacy_replay_backfill_cutoff_at timestamptz not null default now\(\)/i)
  assert.match(migration, /create table public\.payment_verifications/i)
  assert.match(migration, /create table public\.approved_payment_evidence/i)
  assert.match(migration, /create table public\.payment_verification_events/i)
  assert.match(migration, /create table public\.payment_verification_legacy_backfill_results/i)
  assert.match(migration, /create table public\.payment_provider_attestations/i)
  assert.match(migration, /status in \('NOT_CHECKED', 'VERIFIED', 'FAILED', 'UNAVAILABLE'\)/i)
  assert.match(migration, /provider_attestation_id is null/i)
  assert.match(migration, /create unique index approved_payment_evidence_reference_key/i)
  assert.match(migration, /create unique index approved_payment_evidence_raw_image_key/i)
  assert.match(migration, /create unique index approved_payment_evidence_normalized_image_key/i)
  assert.match(migration, /grant execute on function public\.start_payment_verification\(uuid, uuid, boolean\) to service_role/i)
  assert.match(migration, /grant execute on function public\.complete_payment_verification\(uuid, uuid, jsonb\) to service_role/i)
  assert.match(migration, /grant execute on function public\.auto_approve_payment_verification\(uuid\) to service_role/i)
  assert.match(migration, /grant execute on function public\.get_payment_verification_customer_status\(uuid\) to authenticated/i)
  assert.match(migration, /Verification settings are service-only/i)
  assert.match(migration, /grant execute on function public\.update_payment_verification_settings\(boolean, text, text\[\]\) to service_role/i)
  assert.doesNotMatch(migration, /grant execute on function public\.update_payment_verification_settings\(boolean, text, text\[\]\) to authenticated/i)
  assert.match(migration, /grant execute on function public\.record_payment_verification_legacy_backfill\(uuid, text, text, text, text, text, text\) to service_role/i)
  assert.match(migration, /legacy_replay_backfill_complete is distinct from true/i)
  assert.match(migration, /v_reference_fingerprint !~ '\^hmac-sha256:v1:/i)
  assert.match(migration, /not coalesce\(p_force, false\)[\s\S]{0,180}STRONG_MATCH/i)
  assert.match(migration, /create or replace function public\.approve_payment_submission\(\s*p_submission_id uuid/i)
  assert.match(migration, /create or replace function public\.reject_payment_submission\(\s*p_submission_id uuid,\s*p_rejection_reason text/i)
  assert.match(migration, /interval '120 days'/i)
  assert.doesNotMatch(migration, /delete\s+from\s+(public\.)?(payment_submissions|storage\.objects)/i)
  assert.doesNotMatch(migration, /add column auto_approval_enabled[\s\S]{0,160}default\s+true/i)
  assert.doesNotMatch(migration, /default\s+uuid_generate_v4\s*\(/i)
  assert.doesNotMatch(migration, /AUTO_ELIGIBLE|auto_eligible|VALID_SUPPORTED|VALID_UNSUPPORTED|qr_state/i)
})

test('M1.3A migration records bounded fields and excludes raw evidence content', () => {
  assert.match(migration, /never stores raw OCR text or full QR payloads/i)
  assert.match(migration, /raw_image_hash text/i)
  assert.match(migration, /normalized_image_hash text/i)
  assert.match(migration, /reference_fingerprint text/i)
  assert.match(migration, /qr_kind text/i)
  assert.match(migration, /qr_structure_valid boolean/i)
  assert.match(migration, /qr_crc_valid boolean/i)
  assert.match(migration, /reference_extracted boolean/i)
  assert.match(migration, /reason_codes text\[\]/i)
  assert.match(migration, /payment_verification_events_append_only/i)
  assert.match(migration, /alter table public\.payment_verifications enable row level security/i)
  assert.match(migration, /alter table public\.approved_payment_evidence enable row level security/i)
  assert.match(migration, /alter table public\.payment_verification_events enable row level security/i)
  assert.match(migration, /alter table public\.payment_verification_legacy_backfill_results enable row level security/i)
  assert.match(migration, /create policy payment_verifications_manager_select/i)
  assert.doesNotMatch(migration, /payment_verifications_owner_or_manager_select/i)
  assert.match(migration, /get_payment_verification_customer_status/i)
  assert.match(migration, /analyzer_error[\s\S]*ANALYZER_RETRY_LIMIT/i)
  assert.match(migration, /approved_at desc, id desc/i)
  assert.match(migration, /get_payment_verification_legacy_backfill_page/i)
  assert.match(migration, /legacy_replay_backfill_checkpoint_reviewed_at/i)
  assert.match(migration, /provider = 'promptpay_authoritative'/i)
  assert.match(migration, /method = 'promptpay_provider_api_v1'/i)
  assert.match(migration, /status = 'VERIFIED'/i)
  assert.match(migration, /provider_transaction_identity text/i)
  assert.match(migration, /provider_transaction_at timestamptz/i)
  assert.match(migration, /provider_verified_at timestamptz/i)
  assert.match(migration, /valid_until timestamptz/i)
  assert.match(migration, /create unique index payment_provider_attestations_verified_transaction_key/i)
  assert.match(migration, /on public\.payment_provider_attestations \(provider, method, provider_transaction_identity\)/i)
  assert.match(migration, /where status = 'VERIFIED'/i)
  assert.match(migration, /valid_until > now\(\)/i)
  assert.match(migration, /interval '5 minutes'/i)
  assert.match(migration, /pa\.provider_transaction_at >= \([\s\S]{0,180}select o\.created_at - interval '5 minutes'[\s\S]{0,120}where o\.id = v_order_id/i)
  assert.doesNotMatch(migration, /pa\.provider_transaction_at >= \([\s\S]{0,120}select ps\.created_at/i)
  assert.match(migration, /pa\.created_at >= \(select o\.created_at/i)
  assert.match(migration, /pa\.created_at >= \(select ps\.created_at/i)
  assert.match(migration, /provider_verified_at >= provider_transaction_at/i)
  assert.match(migration, /v_provider_attestation_id is null/i)
})
